name: cinema_ticket_app
description: A Flutter app with a beautiful cinema ticket view.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  barcode_flutter: ^1.1.2
  intl: 0.16.1
  google_fonts: ^1.1.0
  dotted_line: ^2.0.1

dev_dependencies:

  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
